<!--Homepage-->

<!--Leafletjs styles and scripts-->
<?php echo $this->headLink()->appendStylesheet('http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css') ?>
<?php echo $this->headScript()->appendFile('http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js') ?>

<!--Placeholder for the map-->
<div id="map"></div>

<table>
    <tr>
        <th>Name</th>
        <th>State</th>
        <th>Walk Score</th>
        <th>Transit Score</th>
        <th>Average Temperature</th>
        <th>Population</th>
        <th>Area</th>
    </tr>

    <?php foreach ($cities as $city) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($city->name);?></td>
            <td><?php echo $this->escapeHtml($stateTable->getState($city->state_id)->name);?></td>
            <td><?php echo $this->escapeHtml($city->walkScore);?></td>
            <td><?php echo $this->escapeHtml($city->transitScore);?></td>
            <td><?php echo $this->escapeHtml($city->avgTemp);?></td>
            <td><?php echo $this->escapeHtml($city->population);?></td>
            <td><?php echo $this->escapeHtml($city->landAreaSquareMiles);?></td>
        </tr>
    <?php endforeach; ?>
</table>

<script>

var map = L.map('map').setView([39.828175, -98.5795], 5);
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: '<?php echo $this->mapboxProjectId; ?>',
    accessToken: '<?php echo $this->mapboxAccessToken; ?>'
}).addTo(map);

function onMarkerClick(e) {
    //alert("You clicked the marker at " + e.latlng);
}

<?php foreach ($cities as $city) : ?>
    var lat  = parseFloat('<?php echo $this->escapeHtml($city->coordinatesNorth);?>');
    var long = parseFloat('<?php echo $this->escapeHtml($city->coordinatesWest);?>');
    var marker = L.marker([lat, long]).addTo(map);
    marker.bindPopup('<?php echo $this->escapeHtml($city->name);?>');
    marker.on('click', onMarkerClick);
<?php endforeach; ?>

</script>
