<!--Homepage-->

<!--Leafletjs styles and scripts-->
<?php echo $this->headLink()->appendStylesheet('http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css') ?>
<?php echo $this->headScript()->appendFile('http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js') ?>

<!--Placeholder for the map-->
<div id="map"></div>

<table>
    <tr>
        <th>Name</th>
        <th>Population</th>
    </tr>

    <?php foreach ($cities as $city) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($city->name);?></td>
            <td><?php echo $this->escapeHtml($city->population);?></td>
        </tr>
    <?php endforeach; ?>
</table>

<script>

var map = L.map('map').setView([51.505, -0.09], 13);
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: '<?php echo $this->mapboxProjectId; ?>',
    accessToken: '<?php echo $this->mapboxAccessToken; ?>'
}).addTo(map);

var marker = L.marker([51.5, -0.09]).addTo(map);
marker.bindPopup("<b>Hello world!</b><br>I am a popup.");

function onMarkerClick(e) {
    alert("You clicked the marker at " + e.latlng);
}

marker.on('click', onMarkerClick);

</script>
