<!--Maps Page-->

<!--Leafletjs styles, Leafletjs scripts, and MaskCanvas plugin scripts-->
<?php echo $this->headLink()->appendStylesheet('http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css')
                            ->appendStylesheet($this->basePath() . '/css/MarkerCluster.css')
                            ->appendStylesheet($this->basePath() . '/css/MarkerCluster.Custom.css')?>
<?php echo $this->headScript()->appendFile('http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js')
                              ->appendFile($this->basePath() . '/js/QuadTree.js')
                              ->appendFile($this->basePath() . '/js/L.TileLayer.MaskCanvas.js')
                              ->appendFile($this->basePath() . '/js/leaflet.markercluster.js')
                              ->appendFile($this->basePath() . '/js/leaflet.markercluster-src.js') ?>

<!--Placeholder for the map-->
<div id="map"></div>

<script>

//City and company location data is loaded via ajax
//Once this data is recieved, the map is created
$.ajax({url: "<?php echo $this->url('application') ?>/index/mapsAjax", dataType: "json"})
       .done(function(data) {
            //separate out the data into different arrays
            var cityData            = data[0];
            var companyLocationData = data[1];

            //create the map, with an inital view of the center of the U.S., somewhat zoomed out, and using mapbox open street map
            var map = L.map('map').setView([39.828175, -98.5795], 5);
            L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
                maxZoom: 18,
                id: '<?php echo $this->mapboxProjectId; ?>',
                accessToken: '<?php echo $this->mapboxAccessToken; ?>'
            }).addTo(map);

            //add a marker to the map for each city, where the marker shows the city information in a popup when clicked
            for (i = 0; i < cityData.length; i++) {
                var marker = L.marker([cityData[i].coordinatesNorth, cityData[i].coordinatesWest]).addTo(map);

                //create the html for the popup
                var info   = '<b>' + cityData[i].cityName + ', ' + cityData[i].stateName + '</b><br>';
                info       = info.concat('Walk Score: ' + cityData[i].walkScore + '<br>');
                info       = info.concat('Transit Score: ' + cityData[i].transitScore + '<br>');
                info       = info.concat('Avg Temp: ' + cityData[i].avgTemp + '<br>');
                info       = info.concat('Population: ' + cityData[i].population + '<br>');
                info       = info.concat('Area: ' + cityData[i].landAreaSquareMiles);

                marker.bindPopup(info);
            }

            //add a clustered marker to the map for each company location
            var companyMarkers = L.markerClusterGroup({spiderfyOnMaxZoom: false}); //data storage for the clustering
            var data           = []; //data storage for the heatmap
            var myIcon         = L.divIcon({className: 'my-div-icon'}); //don't use a visible marker
            for (i = 0; i < companyLocationData.length; i++) {
                //each invisible marker should shows the company name in a popup when clicked
                var marker = L.marker([companyLocationData[i].coordinatesNorth, companyLocationData[i].coordinatesWest], {icon: myIcon});
                marker.bindPopup(companyLocationData[i].companyName);

                companyMarkers.addLayer(marker); //add this company location for the clustering

                data.push([companyLocationData[i].coordinatesNorth, companyLocationData[i].coordinatesWest]); //add this company location for the heatmap
            }
            map.addLayer(companyMarkers); //add the clustering to the map

            //add a heatmap layer, where entire map is darkened and company locations appear as white circles of radius 10
            var layer = L.TileLayer.maskCanvas({radius: 10});
            layer.setData(data); //data includes all the company location coordinates
            map.addLayer(layer); //add the heatmap to the map
  });

</script>
