<!--Maps Page-->

<!--Leafletjs styles, Leafletjs scripts, and MaskCanvas plugin scripts-->
<?php echo $this->headLink()->appendStylesheet('http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css')
                            ->appendStylesheet($this->basePath() . '/css/MarkerCluster.css')
                            ->appendStylesheet($this->basePath() . '/css/MarkerCluster.Custom.css')?>
<?php echo $this->headScript()->appendFile('http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js')
                              ->appendFile($this->basePath() . '/js/QuadTree.js')
                              ->appendFile($this->basePath() . '/js/L.TileLayer.MaskCanvas.js')
                              ->appendFile($this->basePath() . '/js/leaflet.markercluster.js')
                              ->appendFile($this->basePath() . '/js/leaflet.markercluster-src.js') ?>

<!--Placeholder for the map-->
<div id="map"></div>

<script>

var map = L.map('map').setView([39.828175, -98.5795], 5);
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: '<?php echo $this->mapboxProjectId; ?>',
    accessToken: '<?php echo $this->mapboxAccessToken; ?>'
}).addTo(map);

function onCityMarkerClick(e) {
    //alert("You clicked the marker at " + e.latlng);
}

function onCompanyMarkerClick(e) {
    //alert("You clicked the marker at " + e.latlng);
}

<?php foreach ($cities as $city) : ?>
    var lat    = parseFloat('<?php echo $this->escapeHtml($city->coordinatesNorth);?>');
    var long   = parseFloat('<?php echo $this->escapeHtml($city->coordinatesWest);?>');
    var marker = L.marker([lat, long]).addTo(map);
    var info   = '<b><?php echo $this->escapeHtml($city->name) . ', ' . $this->escapeHtml($this->stateTable->getState($city->state_id)->name);?></b><br>';
    info       = info.concat('Walk Score: <?php echo $this->escapeHtml($city->walkScore);?><br>');
    info       = info.concat('Transit Score: <?php echo $this->escapeHtml($city->transitScore);?><br>');
    info       = info.concat('Avg Temp: <?php echo $this->escapeHtml($city->avgTemp);?><br>');
    info       = info.concat('Population: <?php echo $this->escapeHtml($city->population);?><br>');
    info       = info.concat('Area: <?php echo $this->escapeHtml($city->landAreaSquareMiles);?>');
    marker.bindPopup(info);
    marker.on('click', onCityMarkerClick);
<?php endforeach; ?>

var companyMarkers = L.markerClusterGroup({spiderfyOnMaxZoom: false});
var myIcon = L.divIcon({className: 'my-div-icon'});
var data = [];
<?php foreach ($companyLocations as $companyLocation) : ?>
    var marker = L.marker(['<?php echo $this->escapeHtml($companyLocation->coordinatesNorth);?>', '<?php echo $this->escapeHtml($companyLocation->coordinatesWest);?>'], {icon: myIcon});
    marker.bindPopup('<?php echo $this->escapeHtml($companyTable->getCompany($companyLocation->company_id)->name);?>');
    marker.on('click', onCompanyMarkerClick);

    companyMarkers.addLayer(marker);

    data.push(['<?php echo $this->escapeHtml($companyLocation->coordinatesNorth);?>', '<?php echo $this->escapeHtml($companyLocation->coordinatesWest);?>']);
<?php endforeach; ?>
map.addLayer(companyMarkers);

var layer = L.TileLayer.maskCanvas({radius: 10});
layer.setData(data);
map.addLayer(layer);

</script>
