<!--Tables Page, By Company Tab-->

<ul class="nav nav-tabs">
  <li role="presentation"><a href="<?php echo $this->url('application') ?>/index/tablesByCity">By City</a></li>
  <li role="presentation" class="active"><a href="#!">By Company</a></li>
</ul>

<!--DataTables styles and scripts-->
<?php echo $this->headLink()->appendStylesheet($this->basePath() . '/css/jquery.dataTables.css') ?>

<?php echo $this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.js') ?>

<table id="main" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Locations - States</th>
            <th>Locations - Cities</th>
        </tr>
    </thead>
</table>

<script>

$(document).ready(function() {
    var table = $('#main').DataTable({
        "paging": false,
        "ajax": "<?php echo $this->url('application') ?>/index/tablesByCompanyAjax",
        "columns": [
            { "data": "companyName" },
            { "data": "states" },
            { "data": "cities" }
        ],
        "order": [[0, 'asc']]
    });
    $("#main_wrapper").css("padding-top", "5px");
});

</script>
