<!--Tables Page, By City Tab-->

<!--Navigation elements, By City is active-->
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#!">By City</a></li>
  <li role="presentation"><a href="<?php echo $this->url('application') ?>/index/tablesByCompany">By Company</a></li>
</ul>

<!--DataTables styles and scripts-->
<?php echo $this->headLink()->appendStylesheet($this->basePath() . '/css/jquery.dataTables.css') ?>

<?php echo $this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.js') ?>

<!--Table skeleton-->
<table id="main" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>Name</th>
            <th>State</th>
            <th>Walk Score</th>
            <th>Transit Score</th>
            <th>Average Temperature</th>
            <th>Population</th>
            <th>Area</th>
        </tr>
    </thead>
</table>

<script>

//Script to create a child row, filled with the appropriate data
function format (d) {
    //turn the string list of companies into an array
    var companiesArray = d.companies.split(';');
    //html for the start of the table in this child row
    var html = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';

    //add a html row for each company
    var numCompanies = companiesArray.length;
    for (var i = 0; i < numCompanies; i++) {
        html = html.concat('<tr>' +
                              '<td>' + companiesArray[i] +'</td>' +
                           '</tr>');
    }

    //html for the end of the table in this child row
    html = html.concat('</table>')
    return html;
}

$(document).ready(function() {
    //create the data table
    var table = $('#main').DataTable({
        "paging": false,
        "ajax": "<?php echo $this->url('application') ?>/index/tablesByCityAjax",
        "columns": [
            //first column only holds the icon which shows the child row when clicked
            {
                "className":      'details-control',
                "orderable":      false,
                "data":           null,
                "defaultContent": ''
            },
            { "data": "cityName" },
            { "data": "stateName" },
            { "data": "walkScore" },
            { "data": "transitScore" },
            { "data": "avgTemp" },
            { "data": "population" },
            { "data": "landAreaSquareMiles" }
        ],
        "order": [[1, 'asc']] //order by the second column, cityName
    });
    $("#main_wrapper").css("padding-top", "5px"); //add padding to separate table from search box

    //Event listener for opening and closing child rows
    $('#main tbody').on('click', 'td.details-control', function () {
        //find the affected row
        var tr = $(this).closest('tr');
        var row = table.row(tr);

        if (row.child.isShown()) {
            //row is open, close it
            row.child.hide();
            tr.removeClass('shown');
        }
        else {
            //row is closed, open it
            row.child(format(row.data())).show();
            tr.addClass('shown');
        }
    });
});

</script>
